version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: 'Etc/UTC'
    groups:
      minor-and-patch:
        patterns: ['*']
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - automated

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: 'Etc/UTC'
    groups:
      actions-minor-and-patch:
        patterns: ['*']
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - github-actions
      - automated
